[tool.black]
color = true
target-version = ['py37']
extend-exclude = '''
(
  mmdetection/setup.py
  | mmdetection/(_git|.dev_scripts|demo|docs|mmdet|requirements|resources|tests|tools)/*
  | mmdetection/configs/(_base_|albu_example|atss|autoassign|carafe|cascade_rcnn|cascade_rpn|centernet|centripetalnet|cityscapes|common|convnext|cornernet|dcn|dcnv2|ddod|deepfashion|deformable_detr|detectors|detr|double_heads|dyhead|dynamic_rcnn|efficientnet|empirical_attention|fast_rcnn|faster_rcnn|fcos|foveabox|fpg|free_anchor|fsaf|gcnet|gfl|ghm|gn|gn+ws|grid_rcnn|groie|guided_anchoring|hrnet|htc|instaboost|lad|ld|legacy_1.x|libra_rcnn|lvis|mask2former|mask_rcnn|maskformer|ms_rcnn|nas_fcos|nas_fpn|openimages|paa|pafpn|panoptic_fpn|pascal_voc|pisa|point_rend|pvt|queryinst|regnet|reppoints|res2net|resnest|resnet_strikes_back|retinanet|rpn|sabl|scnet|scratch|seesaw_loss|selfsup_pretrain|simple_copy_paste|solo|solov2|sparse_rcnn|ssd|strong_baselines|swin|timm_example|tood|tridentnet|vfnet|wider_face|yolact|yolo|yolof|yolox)/*
)
'''


[tool.isort]
profile = "black"
py_version = 37
atomic = true
float_to_top = true
color_output = true
skip_glob = [
  "mmdetection/setup.py",
  "mmdetection/_git/**",
  "mmdetection/.dev_scripts/**",
  "mmdetection/configs/_base_/**",
  "mmdetection/configs/albu_example/**",
  "mmdetection/configs/atss/**",
  "mmdetection/configs/autoassign/**",
  "mmdetection/configs/carafe/**",
  "mmdetection/configs/cascade_rcnn/**",
  "mmdetection/configs/cascade_rpn/**",
  "mmdetection/configs/centernet/**",
  "mmdetection/configs/centripetalnet/**",
  "mmdetection/configs/cityscapes/**",
  "mmdetection/configs/common/**",
  "mmdetection/configs/convnext/**",
  "mmdetection/configs/cornernet/**",
  "mmdetection/configs/dcn/**",
  "mmdetection/configs/dcnv2/**",
  "mmdetection/configs/ddod/**",
  "mmdetection/configs/deepfashion/**",
  "mmdetection/configs/deformable_detr/**",
  "mmdetection/configs/detectors/**",
  "mmdetection/configs/detr/**",
  "mmdetection/configs/double_heads/**",
  "mmdetection/configs/dyhead/**",
  "mmdetection/configs/dynamic_rcnn/**",
  "mmdetection/configs/efficientnet/**",
  "mmdetection/configs/empirical_attention/**",
  "mmdetection/configs/fast_rcnn/**",
  "mmdetection/configs/faster_rcnn/**",
  "mmdetection/configs/fcos/**",
  "mmdetection/configs/foveabox/**",
  "mmdetection/configs/fpg/**",
  "mmdetection/configs/free_anchor/**",
  "mmdetection/configs/fsaf/**",
  "mmdetection/configs/gcnet/**",
  "mmdetection/configs/gfl/**",
  "mmdetection/configs/ghm/**",
  "mmdetection/configs/gn/**",
  "mmdetection/configs/gn+ws/**",
  "mmdetection/configs/grid_rcnn/**",
  "mmdetection/configs/groie/**",
  "mmdetection/configs/guided_anchoring/**",
  "mmdetection/configs/hrnet/**",
  "mmdetection/configs/htc/**",
  "mmdetection/configs/instaboost/**",
  "mmdetection/configs/lad/**",
  "mmdetection/configs/ld/**",
  "mmdetection/configs/legacy_1.x/**",
  "mmdetection/configs/libra_rcnn/**",
  "mmdetection/configs/lvis/**",
  "mmdetection/configs/mask2former/**",
  "mmdetection/configs/mask_rcnn/**",
  "mmdetection/configs/maskformer/**",
  "mmdetection/configs/ms_rcnn/**",
  "mmdetection/configs/nas_fcos/**",
  "mmdetection/configs/nas_fpn/**",
  "mmdetection/configs/openimages/**",
  "mmdetection/configs/paa/**",
  "mmdetection/configs/pafpn/**",
  "mmdetection/configs/panoptic_fpn/**",
  "mmdetection/configs/pascal_voc/**",
  "mmdetection/configs/pisa/**",
  "mmdetection/configs/point_rend/**",
  "mmdetection/configs/pvt/**",
  "mmdetection/configs/queryinst/**",
  "mmdetection/configs/regnet/**",
  "mmdetection/configs/reppoints/**",
  "mmdetection/configs/res2net/**",
  "mmdetection/configs/resnest/**",
  "mmdetection/configs/resnet_strikes_back/**",
  "mmdetection/configs/retinanet/**",
  "mmdetection/configs/rpn/**",
  "mmdetection/configs/sabl/**",
  "mmdetection/configs/scnet/**",
  "mmdetection/configs/scratch/**",
  "mmdetection/configs/seesaw_loss/**",
  "mmdetection/configs/selfsup_pretrain/**",
  "mmdetection/configs/simple_copy_paste/**",
  "mmdetection/configs/solo/**",
  "mmdetection/configs/solov2/**",
  "mmdetection/configs/sparse_rcnn/**",
  "mmdetection/configs/ssd/**",
  "mmdetection/configs/strong_baselines/**",
  "mmdetection/configs/swin/**",
  "mmdetection/configs/timm_example/**",
  "mmdetection/configs/tood/**",
  "mmdetection/configs/tridentnet/**",
  "mmdetection/configs/vfnet/**",
  "mmdetection/configs/wider_face/**",
  "mmdetection/configs/yolact/**",
  "mmdetection/configs/yolo/**",
  "mmdetection/configs/yolof/**",
  "mmdetection/configs/yolox/**",
  "mmdetection/demo/**",
  "mmdetection/docs/**",
  "mmdetection/mmdet/**",
  "mmdetection/requirements/**",
  "mmdetection/resources/**",
  "mmdetection/tests/**",
  "mmdetection/tools/**",
]
